// src/components/landing/AiDemo.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted, onUnmounted } from 'vue'
import { Sparkles, Send, User, Check } from 'lucide-vue-next'

type InvoiceState = {
  client: string
  clientMeta?: string
  itemLabel: string
  qty: string
  qtyLabel: string
  unitPrice: string
  unitPriceLabel: string
  discountLabel?: string
  discountValue?: string
  dueDays: number
  subtotal: string
  vat: string
  total: string
  invoiceNumber: string
}

type Step = {
  /** What the user types in the chat */
  prompt: string
  /** Short confirmation from the assistant */
  reply: string
  /** Invoice fields after the change is applied */
  invoice: InvoiceState
  /** Which invoice field flashes on update */
  highlight: 'client' | 'qty' | 'discount' | 'due' | 'total'
  /** Optional badge shown when this step is "applied" */
  appliedBadge?: string
}

type Scenario = {
  id: string
  title: string
  /** State shown before the first prompt of the scenario lands */
  initial: InvoiceState
  steps: Step[]
}

const SCENARIOS: Scenario[] = [
  {
    id: 'create',
    title: 'Vystavení nové faktury',
    initial: {
      client: 'Vyberte klienta…',
      itemLabel: 'Položka',
      qty: '—',
      qtyLabel: 'Množství',
      unitPrice: '—',
      unitPriceLabel: 'Cena',
      dueDays: 14,
      subtotal: '0 Kč',
      vat: '0 Kč',
      total: '0 Kč',
      invoiceNumber: '2025-015',
    },
    steps: [
      {
        prompt: 'Vystav fakturu Alze na 10 000 za IT služby.',
        reply: 'Hotovo — Alza, IT služby, 10 000 Kč. Načetl jsem IČO z ARESu.',
        invoice: {
          client: 'Alza.cz a.s.',
          clientMeta: 'IČO 27082440 · Praha 7',
          itemLabel: 'Popis',
          qty: '1',
          qtyLabel: 'Množství',
          unitPrice: '10 000 Kč',
          unitPriceLabel: 'Cena bez DPH',
          dueDays: 14,
          subtotal: '10 000 Kč',
          vat: '2 100 Kč',
          total: '12 100 Kč',
          invoiceNumber: '2025-015',
        },
        highlight: 'client',
        appliedBadge: 'Vytvořeno',
      },
    ],
  },
  {
    id: 'edit',
    title: 'Úprava existující faktury',
    initial: {
      client: 'Marek Dvořák s.r.o.',
      clientMeta: 'IČO 04857321 · Brno',
      itemLabel: 'Položka',
      qty: '16',
      qtyLabel: 'Počet hodin',
      unitPrice: '1 200 Kč',
      unitPriceLabel: 'Sazba / hod',
      dueDays: 7,
      subtotal: '19 200 Kč',
      vat: '4 032 Kč',
      total: '23 232 Kč',
      invoiceNumber: '2025-014',
    },
    steps: [
      {
        prompt: 'Změň počet hodin na 24 a splatnost na 14 dní.',
        reply: 'Hotovo — počet hodin 24, splatnost 14 dní.',
        invoice: {
          client: 'Marek Dvořák s.r.o.',
          clientMeta: 'IČO 04857321 · Brno',
          itemLabel: 'Položka',
          qty: '24',
          qtyLabel: 'Počet hodin',
          unitPrice: '1 200 Kč',
          unitPriceLabel: 'Sazba / hod',
          dueDays: 14,
          subtotal: '28 800 Kč',
          vat: '6 048 Kč',
          total: '34 848 Kč',
          invoiceNumber: '2025-014',
        },
        highlight: 'qty',
        appliedBadge: 'Upraveno',
      },
      {
        prompt: 'Přidej slevu 10 % na celou fakturu.',
        reply: 'Sleva 10 % aplikována, přepočítal jsem DPH.',
        invoice: {
          client: 'Marek Dvořák s.r.o.',
          clientMeta: 'IČO 04857321 · Brno',
          itemLabel: 'Položka',
          qty: '24',
          qtyLabel: 'Počet hodin',
          unitPrice: '1 200 Kč',
          unitPriceLabel: 'Sazba / hod',
          discountLabel: 'Sleva 10 %',
          discountValue: '− 2 880 Kč',
          dueDays: 14,
          subtotal: '25 920 Kč',
          vat: '5 443 Kč',
          total: '31 363 Kč',
          invoiceNumber: '2025-014',
        },
        highlight: 'discount',
        appliedBadge: 'Upraveno',
      },
    ],
  },
]

const TYPING_SPEED = 28 // ms per char
const PAUSE_AFTER_TYPING = 600
const PAUSE_AFTER_APPLY = 2600
const PAUSE_BETWEEN_SCENARIOS = 800

const scenarioIndex = ref(0)
const stepIndex = ref(0)
const typed = ref('')
const phase = ref<'typing' | 'sent' | 'applied'>('typing')
const flashKey = ref(0)

const scenario = computed(() => SCENARIOS[scenarioIndex.value])
const step = computed(() => scenario.value.steps[stepIndex.value])
// Show the previous invoice state until "applied" so the change feels reactive
const shownInvoice = computed<InvoiceState>(() =>
  phase.value === 'applied'
    ? step.value.invoice
    : stepIndex.value === 0
      ? scenario.value.initial
      : scenario.value.steps[stepIndex.value - 1].invoice,
)

let intervalId: number | undefined
const timeouts: number[] = []

function clearTimers() {
  if (intervalId !== undefined) {
    window.clearInterval(intervalId)
    intervalId = undefined
  }
  timeouts.forEach((timeoutId) => window.clearTimeout(timeoutId))
  timeouts.length = 0
}

function runSequence() {
  clearTimers()
  typed.value = ''
  phase.value = 'typing'
  let i = 0
  intervalId = window.setInterval(() => {
    i += 1
    typed.value = step.value.prompt.slice(0, i)
    if (i >= step.value.prompt.length) {
      window.clearInterval(intervalId)
      intervalId = undefined
      const typingPauseId = window.setTimeout(() => {
        phase.value = 'sent'
        const sentPauseId = window.setTimeout(() => {
          phase.value = 'applied'
          flashKey.value += 1
          const applyPauseId = window.setTimeout(() => {
            const isLastStep = stepIndex.value >= scenario.value.steps.length - 1
            if (isLastStep) {
              // Move to next scenario
              const nextScenarioId = window.setTimeout(() => {
                scenarioIndex.value = (scenarioIndex.value + 1) % SCENARIOS.length
                stepIndex.value = 0
              }, PAUSE_BETWEEN_SCENARIOS)
              timeouts.push(nextScenarioId)
            } else {
              stepIndex.value += 1
            }
          }, PAUSE_AFTER_APPLY)
          timeouts.push(applyPauseId)
        }, 700)
        timeouts.push(sentPauseId)
      }, PAUSE_AFTER_TYPING)
      timeouts.push(typingPauseId)
    }
  }, TYPING_SPEED)
}

onMounted(runSequence)
// Re-run the typing/apply cycle whenever the scenario or step changes (React's effect deps)
watch([scenarioIndex, stepIndex], runSequence)
onUnmounted(clearTimers)
</script>

<template>
  <section class="relative overflow-hidden bg-surface py-20 sm:py-28">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-2xl text-center">
        <div
          class="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground"
        >
          <Sparkles class="h-3.5 w-3.5 text-coral" />
          AI asistent — živá ukázka
        </div>
        <h2 class="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
          Napište, co chcete — faktura se vystaví sama
        </h2>
        <p class="mt-4 text-lg text-muted-foreground">
          „Vystav fakturu Alze na 10 000 za IT služby." AI dotáhne IČO z ARESu, spočítá DPH a vyplní
          celý formulář. Klikat můžete pořád ručně — AI je bonus, když spěcháte.
        </p>

        <!-- Scenario indicator -->
        <div
          class="mt-6 inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-1 py-1 text-xs font-medium"
        >
          <span
            v-for="(s, idx) in SCENARIOS"
            :key="s.id"
            class="rounded-full px-3 py-1 transition-colors"
            :class="
              idx === scenarioIndex ? 'bg-coral text-coral-foreground' : 'text-muted-foreground'
            "
          >
            {{ s.title }}
          </span>
        </div>
      </div>

      <div
        class="mx-auto mt-12 grid max-w-5xl grid-cols-1 gap-4 md:grid-cols-2 md:gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]"
      >
        <!-- Chat panel -->
        <div class="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
          <div
            class="flex items-center justify-between border-b border-border bg-surface-soft px-3 py-2 sm:px-5 sm:py-3"
          >
            <div class="flex items-center gap-2">
              <div
                class="flex h-6 w-6 items-center justify-center rounded-lg border border-coral/30 bg-coral/10 text-coral sm:h-7 sm:w-7"
              >
                <Sparkles class="h-3.5 w-3.5" />
              </div>
              <span class="text-xs font-semibold text-foreground sm:text-sm">AI asistent</span>
            </div>
            <span
              class="hidden items-center gap-1.5 text-[11px] font-medium text-muted-foreground sm:inline-flex"
            >
              <span class="h-1.5 w-1.5 rounded-full bg-coral" />
              Online · česky
            </span>
          </div>

          <div
            class="flex min-h-[260px] flex-col gap-2.5 p-3 text-[13px] sm:min-h-[280px] sm:gap-4 sm:p-5 sm:text-sm"
          >
            <!-- Previous assistant reply for context -->
            <div class="flex items-start gap-1.5 sm:gap-2.5">
              <div
                class="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-coral/20 bg-coral/10 text-coral sm:flex"
              >
                <Sparkles class="h-3.5 w-3.5" />
              </div>
              <div
                class="max-w-[95%] break-words rounded-2xl rounded-tl-sm border border-border bg-background px-2.5 py-1.5 leading-snug text-foreground/90 sm:max-w-[85%] sm:px-3.5 sm:py-2"
              >
                {{
                  scenario.id === 'create'
                    ? 'Co potřebujete vystavit? Stačí říct česky.'
                    : 'Tady je vaše faktura. Co mám upravit?'
                }}
              </div>
            </div>

            <!-- User typing -->
            <div class="flex items-start justify-end gap-1.5 sm:gap-2.5">
              <div
                class="max-w-[85%] break-words rounded-2xl rounded-tr-sm bg-coral px-2.5 py-1.5 leading-snug text-coral-foreground shadow-soft sm:max-w-[80%] sm:px-3.5 sm:py-2"
              >
                {{ typed || ' ' }}
                <span
                  v-if="phase === 'typing'"
                  class="ml-0.5 inline-block h-3.5 w-[2px] animate-pulse bg-coral-foreground/80 align-middle"
                />
              </div>
              <div
                class="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-border bg-background text-muted-foreground sm:flex"
              >
                <User class="h-3.5 w-3.5" />
              </div>
            </div>

            <!-- Assistant reply (after sent) -->
            <div v-if="phase !== 'typing'" class="flex items-start gap-1.5 sm:gap-2.5">
              <div
                class="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-coral/20 bg-coral/10 text-coral sm:flex"
              >
                <Sparkles class="h-3.5 w-3.5" />
              </div>
              <div
                class="max-w-[95%] break-words rounded-2xl rounded-tl-sm border border-border bg-background px-2.5 py-1.5 leading-snug text-foreground/90 sm:max-w-[85%] sm:px-3.5 sm:py-2"
              >
                <span
                  v-if="phase === 'sent'"
                  class="inline-flex items-center gap-1 text-muted-foreground"
                >
                  <span
                    class="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60 [animation-delay:-0.2s]"
                  />
                  <span
                    class="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60 [animation-delay:-0.1s]"
                  />
                  <span class="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60" />
                </span>
                <span v-else class="flex items-start gap-1.5">
                  <Check class="mt-0.5 h-3.5 w-3.5 shrink-0 text-coral" />
                  <span class="min-w-0 break-words">{{ step.reply }}</span>
                </span>
              </div>
            </div>
          </div>

          <div class="hidden border-t border-border bg-surface-soft px-5 py-3 sm:block">
            <div
              class="flex items-center gap-2 rounded-xl border border-border bg-background px-3 py-2 text-sm text-muted-foreground"
            >
              <span class="flex-1 truncate">Napište, co potřebujete…</span>
              <button
                type="button"
                class="flex h-7 w-7 items-center justify-center rounded-lg bg-coral text-coral-foreground"
                aria-hidden="true"
                :tabindex="-1"
              >
                <Send class="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
        </div>

        <!-- Invoice preview -->
        <div class="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
          <div
            class="flex items-center justify-between gap-2 border-b border-border bg-surface-soft px-3 py-2 sm:px-5 sm:py-3"
          >
            <div class="flex items-center gap-2">
              <span class="h-2 w-2 rounded-full bg-coral/70 sm:h-2.5 sm:w-2.5" />
              <span
                class="hidden h-2.5 w-2.5 rounded-full bg-muted-foreground/30 sm:inline-block"
              />
              <span
                class="hidden h-2.5 w-2.5 rounded-full bg-muted-foreground/30 sm:inline-block"
              />
              <span class="ml-1 text-[11px] font-semibold text-muted-foreground sm:ml-2 sm:text-xs">
                Faktura {{ shownInvoice.invoiceNumber }}
              </span>
            </div>
            <span
              v-if="phase === 'applied' && step.appliedBadge"
              :key="`badge-${flashKey}`"
              class="inline-flex animate-in fade-in zoom-in-95 items-center gap-1 rounded-full border border-coral/30 bg-coral/10 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-[0.1em] text-coral sm:px-2 sm:text-[10px] sm:tracking-[0.15em]"
            >
              <Sparkles class="h-2.5 w-2.5 sm:h-3 sm:w-3" />
              {{ step.appliedBadge }}
            </span>
          </div>

          <div class="min-h-[420px] space-y-2.5 p-3 sm:min-h-[460px] sm:space-y-4 sm:p-5">
            <!-- Client -->
            <div
              :key="`client-${flashKey}-${shownInvoice.client}`"
              class="rounded-xl border p-2.5 sm:p-4"
              :class="
                step.highlight === 'client' && phase === 'applied'
                  ? 'animate-in fade-in slide-in-from-left-2 border-coral/40 bg-coral/5'
                  : 'border-border bg-background'
              "
            >
              <div
                class="text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground sm:text-[10px] sm:tracking-[0.15em]"
              >
                Klient
              </div>
              <div
                class="mt-0.5 text-[13px] font-semibold leading-tight text-foreground sm:mt-1 sm:text-sm"
              >
                {{ shownInvoice.client }}
              </div>
              <div
                v-if="shownInvoice.clientMeta"
                class="mt-0.5 text-[10px] leading-tight text-muted-foreground sm:text-xs"
              >
                {{ shownInvoice.clientMeta }}
              </div>
            </div>

            <!-- Line item -->
            <div class="rounded-xl border border-border bg-background p-2.5 sm:p-4">
              <div
                class="text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground sm:text-xs sm:tracking-[0.15em]"
              >
                {{ shownInvoice.itemLabel }}
              </div>
              <div
                class="mt-0.5 text-[12px] font-medium leading-tight text-foreground sm:mt-1 sm:text-sm"
              >
                {{ scenario.id === 'create' ? 'IT služby' : 'Konzultace · webový vývoj' }}
              </div>
              <div class="mt-2 grid grid-cols-3 gap-1.5 text-xs sm:mt-3 sm:gap-3">
                <div
                  :key="
                    step.highlight === 'qty' && phase === 'applied'
                      ? `f-qty-${flashKey}`
                      : undefined
                  "
                  class="rounded-lg border border-border/70 bg-surface-soft px-1.5 py-1.5 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0"
                >
                  <div
                    class="truncate text-[8px] font-semibold uppercase leading-tight tracking-[0.08em] text-muted-foreground sm:text-[10px] sm:tracking-[0.12em]"
                  >
                    <span class="sm:hidden">{{ shownInvoice.qtyLabel }}</span>
                    <span class="hidden sm:inline">{{ shownInvoice.qtyLabel }}</span>
                  </div>
                  <div
                    class="mt-1 inline-block max-w-full rounded px-1 py-0.5 text-[10px] font-semibold leading-tight text-foreground sm:mt-0.5 sm:px-1.5 sm:text-sm"
                    :class="
                      step.highlight === 'qty' && phase === 'applied'
                        ? 'animate-in fade-in zoom-in-95 bg-coral/15 text-coral'
                        : ''
                    "
                  >
                    {{ shownInvoice.qty }}
                  </div>
                </div>
                <div
                  class="rounded-lg border border-border/70 bg-surface-soft px-1.5 py-1.5 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0"
                >
                  <div
                    class="truncate text-[8px] font-semibold uppercase leading-tight tracking-[0.08em] text-muted-foreground sm:text-[10px] sm:tracking-[0.12em]"
                  >
                    <span class="sm:hidden">{{ shownInvoice.unitPriceLabel }}</span>
                    <span class="hidden sm:inline">{{ shownInvoice.unitPriceLabel }}</span>
                  </div>
                  <div
                    class="mt-1 inline-block max-w-full rounded px-1 py-0.5 text-[10px] font-semibold leading-tight text-foreground sm:mt-0.5 sm:px-1.5 sm:text-sm"
                  >
                    {{ shownInvoice.unitPrice }}
                  </div>
                </div>
                <div
                  :key="
                    step.highlight === 'due' && phase === 'applied'
                      ? `f-due-${flashKey}`
                      : undefined
                  "
                  class="rounded-lg border border-border/70 bg-surface-soft px-1.5 py-1.5 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0"
                >
                  <div
                    class="truncate text-[8px] font-semibold uppercase leading-tight tracking-[0.08em] text-muted-foreground sm:text-[10px] sm:tracking-[0.12em]"
                  >
                    <span class="sm:hidden">Splat.</span>
                    <span class="hidden sm:inline">Splatnost</span>
                  </div>
                  <div
                    class="mt-1 inline-block max-w-full rounded px-1 py-0.5 text-[10px] font-semibold leading-tight text-foreground sm:mt-0.5 sm:px-1.5 sm:text-sm"
                    :class="
                      step.highlight === 'due' && phase === 'applied'
                        ? 'animate-in fade-in zoom-in-95 bg-coral/15 text-coral'
                        : ''
                    "
                  >
                    {{ `${shownInvoice.dueDays} dní` }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Totals -->
            <div
              class="space-y-1 rounded-xl border border-border bg-background p-2.5 text-[12px] sm:space-y-1.5 sm:p-4 sm:text-sm"
            >
              <div class="flex items-center justify-between">
                <span class="text-muted-foreground">Mezisoučet</span>
                <span class="font-semibold text-foreground">{{ shownInvoice.subtotal }}</span>
              </div>
              <div
                v-if="shownInvoice.discountLabel"
                :key="
                  step.highlight === 'discount' && phase === 'applied'
                    ? `r-discount-${flashKey}`
                    : undefined
                "
                class="flex items-center justify-between"
                :class="
                  step.highlight === 'discount' && phase === 'applied'
                    ? 'animate-in fade-in slide-in-from-right-2'
                    : ''
                "
              >
                <span class="text-coral">{{ shownInvoice.discountLabel }}</span>
                <span class="font-semibold text-coral">{{ shownInvoice.discountValue ?? '' }}</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-muted-foreground">DPH 21 %</span>
                <span class="font-semibold text-foreground">{{ shownInvoice.vat }}</span>
              </div>
              <div class="my-1.5 h-px bg-border sm:my-2" />
              <div
                :key="`total-${flashKey}`"
                class="flex items-baseline justify-between gap-1"
                :class="phase === 'applied' ? 'animate-in fade-in slide-in-from-bottom-1' : ''"
              >
                <span class="text-[11px] font-semibold leading-tight text-foreground sm:text-sm">
                  Celkem
                </span>
                <span class="text-base font-extrabold tracking-tight text-foreground sm:text-xl">
                  {{ shownInvoice.total }}
                </span>
              </div>
            </div>

            <p class="hidden text-center text-xs text-muted-foreground sm:block">
              ⏱ Od zprávy k hotové faktuře — méně než vteřina.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// src/components/landing/AiDemo.tsx
import { useEffect, useState } from "react";
import { Sparkles, Send, User, Check } from "lucide-react";

type InvoiceState = {
  client: string;
  clientMeta?: string;
  itemLabel: string;
  qty: string;
  qtyLabel: string;
  unitPrice: string;
  unitPriceLabel: string;
  discountLabel?: string;
  discountValue?: string;
  dueDays: number;
  subtotal: string;
  vat: string;
  total: string;
  invoiceNumber: string;
};

type Step = {
  /** What the user types in the chat */
  prompt: string;
  /** Short confirmation from the assistant */
  reply: string;
  /** Invoice fields after the change is applied */
  invoice: InvoiceState;
  /** Which invoice field flashes on update */
  highlight: "client" | "qty" | "discount" | "due" | "total";
  /** Optional badge shown when this step is "applied" */
  appliedBadge?: string;
};

type Scenario = {
  id: string;
  title: string;
  /** State shown before the first prompt of the scenario lands */
  initial: InvoiceState;
  steps: Step[];
};

const SCENARIOS: Scenario[] = [
  {
    id: "create",
    title: "Vystavení nové faktury",
    initial: {
      client: "Vyberte klienta…",
      itemLabel: "Položka",
      qty: "—",
      qtyLabel: "Množství",
      unitPrice: "—",
      unitPriceLabel: "Cena",
      dueDays: 14,
      subtotal: "0 Kč",
      vat: "0 Kč",
      total: "0 Kč",
      invoiceNumber: "2025-015",
    },
    steps: [
      {
        prompt: "Vystav fakturu Alze na 10 000 za IT služby.",
        reply: "Hotovo — Alza, IT služby, 10 000 Kč. Načetl jsem IČO z ARESu.",
        invoice: {
          client: "Alza.cz a.s.",
          clientMeta: "IČO 27082440 · Praha 7",
          itemLabel: "Popis",
          qty: "1",
          qtyLabel: "Množství",
          unitPrice: "10 000 Kč",
          unitPriceLabel: "Cena bez DPH",
          dueDays: 14,
          subtotal: "10 000 Kč",
          vat: "2 100 Kč",
          total: "12 100 Kč",
          invoiceNumber: "2025-015",
        },
        highlight: "client",
        appliedBadge: "Vytvořeno",
      },
    ],
  },
  {
    id: "edit",
    title: "Úprava existující faktury",
    initial: {
      client: "Marek Dvořák s.r.o.",
      clientMeta: "IČO 04857321 · Brno",
      itemLabel: "Položka",
      qty: "16",
      qtyLabel: "Počet hodin",
      unitPrice: "1 200 Kč",
      unitPriceLabel: "Sazba / hod",
      dueDays: 7,
      subtotal: "19 200 Kč",
      vat: "4 032 Kč",
      total: "23 232 Kč",
      invoiceNumber: "2025-014",
    },
    steps: [
      {
        prompt: "Změň počet hodin na 24 a splatnost na 14 dní.",
        reply: "Hotovo — počet hodin 24, splatnost 14 dní.",
        invoice: {
          client: "Marek Dvořák s.r.o.",
          clientMeta: "IČO 04857321 · Brno",
          itemLabel: "Položka",
          qty: "24",
          qtyLabel: "Počet hodin",
          unitPrice: "1 200 Kč",
          unitPriceLabel: "Sazba / hod",
          dueDays: 14,
          subtotal: "28 800 Kč",
          vat: "6 048 Kč",
          total: "34 848 Kč",
          invoiceNumber: "2025-014",
        },
        highlight: "qty",
        appliedBadge: "Upraveno",
      },
      {
        prompt: "Přidej slevu 10 % na celou fakturu.",
        reply: "Sleva 10 % aplikována, přepočítal jsem DPH.",
        invoice: {
          client: "Marek Dvořák s.r.o.",
          clientMeta: "IČO 04857321 · Brno",
          itemLabel: "Položka",
          qty: "24",
          qtyLabel: "Počet hodin",
          unitPrice: "1 200 Kč",
          unitPriceLabel: "Sazba / hod",
          discountLabel: "Sleva 10 %",
          discountValue: "− 2 880 Kč",
          dueDays: 14,
          subtotal: "25 920 Kč",
          vat: "5 443 Kč",
          total: "31 363 Kč",
          invoiceNumber: "2025-014",
        },
        highlight: "discount",
        appliedBadge: "Upraveno",
      },
    ],
  },
];

const TYPING_SPEED = 28; // ms per char
const PAUSE_AFTER_TYPING = 600;
const PAUSE_AFTER_APPLY = 2600;
const PAUSE_BETWEEN_SCENARIOS = 800;

export function AiDemo() {
  const [scenarioIndex, setScenarioIndex] = useState(0);
  const [stepIndex, setStepIndex] = useState(0);
  const [typed, setTyped] = useState("");
  const [phase, setPhase] = useState<"typing" | "sent" | "applied">("typing");
  const [flashKey, setFlashKey] = useState(0);

  const scenario = SCENARIOS[scenarioIndex];
  const step = scenario.steps[stepIndex];
  // Show the previous invoice state until "applied" so the change feels reactive
  const shownInvoice: InvoiceState =
    phase === "applied"
      ? step.invoice
      : stepIndex === 0
        ? scenario.initial
        : scenario.steps[stepIndex - 1].invoice;

  useEffect(() => {
    setTyped("");
    setPhase("typing");
    const timeouts: number[] = [];
    let i = 0;
    const intervalId = window.setInterval(() => {
      i += 1;
      setTyped(step.prompt.slice(0, i));
      if (i >= step.prompt.length) {
        window.clearInterval(intervalId);
        const typingPauseId = window.setTimeout(() => {
          setPhase("sent");
          const sentPauseId = window.setTimeout(() => {
            setPhase("applied");
            setFlashKey((k) => k + 1);
            const applyPauseId = window.setTimeout(() => {
              const isLastStep = stepIndex >= scenario.steps.length - 1;
              if (isLastStep) {
                // Move to next scenario
                const nextScenarioId = window.setTimeout(() => {
                  setScenarioIndex((s) => (s + 1) % SCENARIOS.length);
                  setStepIndex(0);
                }, PAUSE_BETWEEN_SCENARIOS);
                timeouts.push(nextScenarioId);
              } else {
                setStepIndex((s) => s + 1);
              }
            }, PAUSE_AFTER_APPLY);
            timeouts.push(applyPauseId);
          }, 700);
          timeouts.push(sentPauseId);
        }, PAUSE_AFTER_TYPING);
        timeouts.push(typingPauseId);
      }
    }, TYPING_SPEED);
    return () => {
      window.clearInterval(intervalId);
      timeouts.forEach((timeoutId) => window.clearTimeout(timeoutId));
    };
  }, [scenarioIndex, stepIndex, step.prompt, scenario.steps.length]);

  return (
    <section className="relative overflow-hidden bg-surface py-20 sm:py-28">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-coral" />
            AI asistent — živá ukázka
          </div>
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Napište, co chcete — faktura se vystaví sama
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            „Vystav fakturu Alze na 10 000 za IT služby." AI dotáhne IČO z ARESu, spočítá DPH a
            vyplní celý formulář. Klikat můžete pořád ručně — AI je bonus, když spěcháte.
          </p>

          {/* Scenario indicator */}
          <div className="mt-6 inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-1 py-1 text-xs font-medium">
            {SCENARIOS.map((s, idx) => (
              <span
                key={s.id}
                className={`rounded-full px-3 py-1 transition-colors ${
                  idx === scenarioIndex
                    ? "bg-coral text-coral-foreground"
                    : "text-muted-foreground"
                }`}
              >
                {s.title}
              </span>
            ))}
          </div>
        </div>

        <div className="mx-auto mt-12 grid max-w-5xl grid-cols-1 gap-4 md:grid-cols-2 md:gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]">
          {/* Chat panel */}
          <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
            <div className="flex items-center justify-between border-b border-border bg-surface-soft px-3 py-2 sm:px-5 sm:py-3">
              <div className="flex items-center gap-2">
                <div className="flex h-6 w-6 items-center justify-center rounded-lg border border-coral/30 bg-coral/10 text-coral sm:h-7 sm:w-7">
                  <Sparkles className="h-3.5 w-3.5" />
                </div>
                <span className="text-xs font-semibold text-foreground sm:text-sm">AI asistent</span>
              </div>
              <span className="hidden items-center gap-1.5 text-[11px] font-medium text-muted-foreground sm:inline-flex">
                <span className="h-1.5 w-1.5 rounded-full bg-coral" />
                Online · česky
              </span>
            </div>

            <div className="flex min-h-[260px] flex-col gap-2.5 p-3 text-[13px] sm:min-h-[280px] sm:gap-4 sm:p-5 sm:text-sm">
              {/* Previous assistant reply for context */}
              <div className="flex items-start gap-1.5 sm:gap-2.5">
                <div className="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-coral/20 bg-coral/10 text-coral sm:flex">
                  <Sparkles className="h-3.5 w-3.5" />
                </div>
                <div className="max-w-[95%] break-words rounded-2xl rounded-tl-sm border border-border bg-background px-2.5 py-1.5 leading-snug text-foreground/90 sm:max-w-[85%] sm:px-3.5 sm:py-2">
                  {scenario.id === "create"
                    ? "Co potřebujete vystavit? Stačí říct česky."
                    : "Tady je vaše faktura. Co mám upravit?"}
                </div>
              </div>

              {/* User typing */}
              <div className="flex items-start justify-end gap-1.5 sm:gap-2.5">
                <div className="max-w-[85%] break-words rounded-2xl rounded-tr-sm bg-coral px-2.5 py-1.5 leading-snug text-coral-foreground shadow-soft sm:max-w-[80%] sm:px-3.5 sm:py-2">
                  {typed || "\u00A0"}
                  {phase === "typing" && (
                    <span className="ml-0.5 inline-block h-3.5 w-[2px] animate-pulse bg-coral-foreground/80 align-middle" />
                  )}
                </div>
                <div className="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-border bg-background text-muted-foreground sm:flex">
                  <User className="h-3.5 w-3.5" />
                </div>
              </div>

              {/* Assistant reply (after sent) */}
              {phase !== "typing" && (
                <div className="flex items-start gap-1.5 sm:gap-2.5">
                  <div className="hidden h-7 w-7 flex-none items-center justify-center rounded-full border border-coral/20 bg-coral/10 text-coral sm:flex">
                    <Sparkles className="h-3.5 w-3.5" />
                  </div>
                  <div className="max-w-[95%] break-words rounded-2xl rounded-tl-sm border border-border bg-background px-2.5 py-1.5 leading-snug text-foreground/90 sm:max-w-[85%] sm:px-3.5 sm:py-2">
                    {phase === "sent" ? (
                      <span className="inline-flex items-center gap-1 text-muted-foreground">
                        <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60 [animation-delay:-0.2s]" />
                        <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60 [animation-delay:-0.1s]" />
                        <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-muted-foreground/60" />
                      </span>
                    ) : (
                      <span className="flex items-start gap-1.5">
                        <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-coral" />
                        <span className="min-w-0 break-words">{step.reply}</span>
                      </span>
                    )}
                  </div>
                </div>
              )}
            </div>

            <div className="hidden border-t border-border bg-surface-soft px-5 py-3 sm:block">
              <div className="flex items-center gap-2 rounded-xl border border-border bg-background px-3 py-2 text-sm text-muted-foreground">
                <span className="flex-1 truncate">Napište, co potřebujete…</span>
                <button
                  type="button"
                  className="flex h-7 w-7 items-center justify-center rounded-lg bg-coral text-coral-foreground"
                  aria-hidden="true"
                  tabIndex={-1}
                >
                  <Send className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          </div>

          {/* Invoice preview */}
          <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-card">
            <div className="flex items-center justify-between gap-2 border-b border-border bg-surface-soft px-3 py-2 sm:px-5 sm:py-3">
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-coral/70 sm:h-2.5 sm:w-2.5" />
                <span className="hidden h-2.5 w-2.5 rounded-full bg-muted-foreground/30 sm:inline-block" />
                <span className="hidden h-2.5 w-2.5 rounded-full bg-muted-foreground/30 sm:inline-block" />
                <span className="ml-1 text-[11px] font-semibold text-muted-foreground sm:ml-2 sm:text-xs">
                  Faktura {shownInvoice.invoiceNumber}
                </span>
              </div>
              {phase === "applied" && step.appliedBadge && (
                <span
                  key={`badge-${flashKey}`}
                  className="inline-flex animate-in fade-in zoom-in-95 items-center gap-1 rounded-full border border-coral/30 bg-coral/10 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-[0.1em] text-coral sm:px-2 sm:text-[10px] sm:tracking-[0.15em]"
                >
                  <Sparkles className="h-2.5 w-2.5 sm:h-3 sm:w-3" />
                  {step.appliedBadge}
                </span>
              )}
            </div>

            <div className="space-y-2.5 p-3 sm:space-y-4 sm:p-5">
              {/* Client */}
              <div
                key={`client-${flashKey}-${shownInvoice.client}`}
                className={`rounded-xl border p-2.5 sm:p-4 ${
                  step.highlight === "client" && phase === "applied"
                    ? "animate-in fade-in slide-in-from-left-2 border-coral/40 bg-coral/5"
                    : "border-border bg-background"
                }`}
              >
                <div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground sm:text-[10px] sm:tracking-[0.15em]">
                  Klient
                </div>
                <div className="mt-0.5 text-[13px] font-semibold leading-tight text-foreground sm:mt-1 sm:text-sm">
                  {shownInvoice.client}
                </div>
                {shownInvoice.clientMeta && (
                  <div className="mt-0.5 text-[10px] leading-tight text-muted-foreground sm:text-xs">
                    {shownInvoice.clientMeta}
                  </div>
                )}
              </div>

              {/* Line item */}
              <div className="rounded-xl border border-border bg-background p-2.5 sm:p-4">
                <div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground sm:text-xs sm:tracking-[0.15em]">
                  {shownInvoice.itemLabel}
                </div>
                <div className="mt-0.5 text-[12px] font-medium leading-tight text-foreground sm:mt-1 sm:text-sm">
                  {scenario.id === "create"
                    ? "IT služby"
                    : "Konzultace · webový vývoj"}
                </div>
                <div className="mt-2 grid grid-cols-3 gap-1.5 text-xs sm:mt-3 sm:gap-3">
                  <Field
                    label={shownInvoice.qtyLabel}
                    value={shownInvoice.qty}
                    flash={step.highlight === "qty" && phase === "applied"}
                    flashKey={flashKey}
                  />
                  <Field label={shownInvoice.unitPriceLabel} value={shownInvoice.unitPrice} />
                  <Field
                    label="Splatnost"
                    mobileLabel="Splat."
                    value={`${shownInvoice.dueDays} dní`}
                    flash={step.highlight === "due" && phase === "applied"}
                    flashKey={flashKey}
                  />
                </div>
              </div>

              {/* Totals */}
              <div className="space-y-1 rounded-xl border border-border bg-background p-2.5 text-[12px] sm:space-y-1.5 sm:p-4 sm:text-sm">
                <Row label="Mezisoučet" value={shownInvoice.subtotal} />
                {shownInvoice.discountLabel && (
                  <Row
                    label={shownInvoice.discountLabel}
                    value={shownInvoice.discountValue ?? ""}
                    flash={step.highlight === "discount" && phase === "applied"}
                    flashKey={flashKey}
                    accent
                  />
                )}
                <Row label="DPH 21 %" value={shownInvoice.vat} />
                <div className="my-1.5 h-px bg-border sm:my-2" />
                <div
                  key={`total-${flashKey}`}
                  className={`flex items-baseline justify-between gap-1 ${
                    phase === "applied" ? "animate-in fade-in slide-in-from-bottom-1" : ""
                  }`}
                >
                  <span className="text-[11px] font-semibold leading-tight text-foreground sm:text-sm">Celkem</span>
                  <span className="text-base font-extrabold tracking-tight text-foreground sm:text-xl">
                    {shownInvoice.total}
                  </span>
                </div>
              </div>

              <p className="hidden text-center text-xs text-muted-foreground sm:block">
                ⏱ Od zprávy k hotové faktuře — méně než vteřina.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Field({
  label,
  mobileLabel,
  value,
  flash,
  flashKey,
}: {
  label: string;
  mobileLabel?: string;
  value: string;
  flash?: boolean;
  flashKey?: number;
}) {
  return (
    <div className="rounded-lg border border-border/70 bg-surface-soft px-1.5 py-1.5 sm:rounded-none sm:border-0 sm:bg-transparent sm:p-0">
      <div className="truncate text-[8px] font-semibold uppercase leading-tight tracking-[0.08em] text-muted-foreground sm:text-[10px] sm:tracking-[0.12em]">
        <span className="sm:hidden">{mobileLabel ?? label}</span>
        <span className="hidden sm:inline">{label}</span>
      </div>
      <div
        key={flash ? `f-${flashKey}` : undefined}
        className={`mt-1 inline-block max-w-full rounded px-1 py-0.5 text-[10px] font-semibold leading-tight text-foreground sm:mt-0.5 sm:px-1.5 sm:text-sm ${
          flash ? "animate-in fade-in zoom-in-95 bg-coral/15 text-coral" : ""
        }`}
      >
        {value}
      </div>
    </div>
  );
}

function Row({
  label,
  value,
  flash,
  flashKey,
  accent,
}: {
  label: string;
  value: string;
  flash?: boolean;
  flashKey?: number;
  accent?: boolean;
}) {
  return (
    <div
      key={flash ? `r-${flashKey}` : undefined}
      className={`flex items-center justify-between ${
        flash ? "animate-in fade-in slide-in-from-right-2" : ""
      }`}
    >
      <span className={accent ? "text-coral" : "text-muted-foreground"}>{label}</span>
      <span className={`font-semibold ${accent ? "text-coral" : "text-foreground"}`}>{value}</span>
    </div>
  );
}
