// src/components/landing/PricingTeaser.tsx
import { Button } from "@/components/ui/button";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";

const includes = [
  "Neomezené faktury i klienti",
  "AI asistent v češtině",
  "QR platby a načítání z ARESu",
  "Automatické DPH a upomínky",
];

export function PricingTeaser() {
  return (
    <section className="bg-surface-soft py-16 sm:py-20">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl">
            Začni zdarma. Plať, až ti to vydělává.
          </h2>
          <p className="mt-4 text-base leading-relaxed text-muted-foreground sm:text-lg">
            14 dní zdarma bez karty. Potom plný přístup od{" "}
            <span className="font-semibold text-foreground">100 Kč/měsíc</span>{" "}
            při roční platbě. Neomezené faktury, klienti, AI asistent a všechny
            hlavní funkce v ceně.
          </p>
        </div>

        <div className="mx-auto mt-10 max-w-2xl rounded-2xl border border-border bg-card p-6 shadow-card sm:p-8">
          <div className="flex flex-col items-center gap-2 text-center">
            <div className="flex items-end gap-2">
              <span className="text-5xl font-extrabold tracking-tight text-foreground sm:text-6xl">
                100
              </span>
              <div className="pb-2 text-left">
                <p className="text-base font-semibold text-foreground">Kč/měs</p>
                <p className="text-xs text-muted-foreground">při ročním placení</p>
              </div>
            </div>
            <p className="text-sm text-muted-foreground">
              Měsíční tarif 159 Kč/měs. Cena je konečná — neplátce DPH.
            </p>
          </div>

          <ul className="mx-auto mt-6 grid max-w-md gap-2.5 sm:grid-cols-2">
            {includes.map((it) => (
              <li key={it} className="flex items-start gap-2 text-sm text-foreground/90">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-coral/15 text-coral">
                  <Check className="h-3 w-3" />
                </span>
                {it}
              </li>
            ))}
          </ul>

          <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
            <Button variant="coral" size="lg" asChild className="w-full sm:w-auto">
              <a href="/registrace">Začít zdarma</a>
            </Button>
            <Button variant="outline" size="lg" asChild className="group w-full sm:w-auto">
              <Link to="/cenik">
                Zobrazit ceník
                <ArrowRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-0.5" />
              </Link>
            </Button>
          </div>
          <p className="mt-3 text-center text-xs text-muted-foreground">
            Žádné závazky. Kdykoli můžeš skončit.
          </p>
        </div>
      </div>
    </section>
  );
}

// src/components/landing/PricingTeaser.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { ArrowRight } from 'lucide-vue-next'
import { Button } from '@/components/ui/button'
import { PRICING_MODULES, MODULAR_PRICING } from '@/lib/pricing'

const minPrice = Math.min(...PRICING_MODULES.map((m) => m.monthly))
const czk = (n: number) => n.toLocaleString('cs-CZ')
</script>

<template>
  <section id="cenik" class="relative overflow-hidden bg-background py-16 sm:py-20">
    <div
      class="pointer-events-none absolute left-1/2 top-0 -z-10 aspect-square w-[120%] max-w-3xl -translate-x-1/2 -translate-y-1/3 rounded-full bg-aura opacity-20 blur-3xl"
      aria-hidden="true"
    />
    <div class="mx-auto max-w-3xl px-4 text-center sm:px-6 lg:px-8">
      <p
        class="flex items-center justify-center gap-3 font-mono text-[0.7rem] font-medium uppercase tracking-[0.22em] text-muted-foreground"
      >
        <span class="h-px w-7 bg-coral" aria-hidden="true" />
        Ceník
        <span class="h-px w-7 bg-coral" aria-hidden="true" />
      </p>
      <h2 class="mt-5 font-display text-3xl font-black tracking-tight text-foreground sm:text-4xl">
        Zaplatíte jen za to, co používáte.
      </h2>
      <p class="mx-auto mt-4 max-w-xl text-base text-muted-foreground sm:text-lg">
        Žádný předražený kolos. Poskládejte si systém z modulů, které váš provoz reálně potřebuje —
        a přidávejte další, až porostete.
      </p>

      <!-- Modulární náhled -->
      <div class="mt-7 flex flex-wrap justify-center gap-2">
        <span
          v-for="m in PRICING_MODULES"
          :key="m.key"
          class="rounded-full border border-border bg-card px-3 py-1.5 text-sm font-medium text-foreground"
        >
          {{ m.name }}
        </span>
      </div>

      <p class="mt-6 text-sm text-muted-foreground">
        Už od <span class="font-mono font-bold text-foreground">{{ czk(minPrice) }} Kč/měs</span> ·
        kompletní balík za
        <span class="font-mono font-bold text-foreground"
          >{{ czk(MODULAR_PRICING.bundleAllMonthly) }} Kč/měs</span
        >
        · {{ MODULAR_PRICING.trialDays }} dní zdarma
      </p>

      <div class="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
        <Button variant="coral" size="xl" class="group w-full sm:w-auto" as-child>
          <RouterLink to="/cenik">
            Spočítat cenu
            <ArrowRight class="transition-transform group-hover:translate-x-0.5" />
          </RouterLink>
        </Button>
        <Button variant="outline" size="xl" class="w-full sm:w-auto" as-child>
          <RouterLink to="/registrace">Vyzkoušet zdarma</RouterLink>
        </Button>
      </div>
    </div>
  </section>
</template>
