// src/components/app/SendInvoiceDialog.tsx
import { useEffect, useState } from "react";
import { Loader2, Mail, Send, Paperclip } from "lucide-react";
import { toast } from "sonner";

import { supabase } from "@/integrations/supabase/client";
import { useServerFn } from "@tanstack/react-start";
import { sendInvoiceEmail } from "@/lib/email/send-invoice.functions";
import { renderInvoicePdfBlob } from "@/lib/invoice-pdf";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export type SendInvoiceContext = {
  invoiceId: string;
  invoiceNumber: string;
  recipientEmail?: string | null;
  recipientName?: string | null;
  supplierName?: string | null;
  total?: number;
  currency?: string;
  dueDate?: string;
  /** Element ID s vyrenderovaným <InvoiceDocument/> připraveným pro html2canvas. */
  pdfElementId: string;
};

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  context: SendInvoiceContext | null;
  onSent?: () => void;
};

export function SendInvoiceDialog({ open, onOpenChange, context, onSent }: Props) {
  const sendFn = useServerFn(sendInvoiceEmail);
  const [to, setTo] = useState("");
  const [cc, setCc] = useState("");
  const [subject, setSubject] = useState("");
  const [personalNote, setPersonalNote] = useState("");
  const [sending, setSending] = useState(false);

  useEffect(() => {
    if (!context || !open) return;
    setTo(context.recipientEmail ?? "");
    setCc("");
    const supplier = context.supplierName ?? "";
    setSubject(`Faktura ${context.invoiceNumber}${supplier ? ` od ${supplier}` : ""}`);
    setPersonalNote("");
  }, [context, open]);

  if (!context) return null;

  const handleSend = async () => {
    if (!to.trim()) {
      toast.error("Zadejte e-mail příjemce.");
      return;
    }
    setSending(true);
    try {
      // 1) Vygeneruj PDF z DOM
      const blob = await renderInvoicePdfBlob(context.pdfElementId);

      // 2) Nahraj do Storage pod {user_id}/{invoice_id}.pdf
      const { data: userData, error: userErr } = await supabase.auth.getUser();
      if (userErr || !userData.user) throw new Error("Nejste přihlášeni.");
      const path = `${userData.user.id}/${context.invoiceId}.pdf`;
      const { error: upErr } = await supabase.storage
        .from("invoices")
        .upload(path, blob, { upsert: true, contentType: "application/pdf" });
      if (upErr) throw new Error("Nahrání PDF selhalo: " + upErr.message);

      // 3) Získej access token pro server fn
      const { data: sess } = await supabase.auth.getSession();
      const token = sess.session?.access_token;
      if (!token) throw new Error("Chybí přihlašovací token.");

      // 4) Zavolej server funkci s Authorization header
      await sendFn({
        data: {
          invoiceId: context.invoiceId,
          pdfPath: path,
          to: to.trim(),
          cc: cc.trim() || undefined,
          subject: subject.trim(),
          personalNote: personalNote.trim() || undefined,
          filename: `${context.invoiceNumber}.pdf`,
        },
        headers: { Authorization: `Bearer ${token}` },
      });

      // Bug #2: update statusu draft → issued provedeme na klientovi,
      // aby update proběhl pod RLS autentizovaného uživatele.
      const { error: statusErr } = await supabase
        .from("invoices")
        .update({ status: "issued" })
        .eq("id", context.invoiceId)
        .eq("status", "draft");
      if (statusErr) {
        console.warn("Aktualizace stavu faktury selhala:", statusErr);
      }

      // Bug #3: explicitní success toast s delším trváním, ať je vidět.
      toast.success("E-mail odeslán", {
        description: `Faktura ${context.invoiceNumber} byla odeslána na ${to.trim()}.`,
        duration: 6000,
      });
      onOpenChange(false);
      onSent?.();
    } catch (e) {
      console.error(e);
      toast.error(e instanceof Error ? e.message : "Odeslání selhalo.");
    } finally {
      setSending(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={(o) => !sending && onOpenChange(o)}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Mail className="h-5 w-5 text-primary" />
            Odeslat fakturu e-mailem
          </DialogTitle>
          <DialogDescription>
            Faktura {context.invoiceNumber} bude odeslána jako PDF v příloze.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="send-to">Příjemce *</Label>
            <Input
              id="send-to"
              type="email"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="klient@example.com"
              disabled={sending}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="send-cc">Kopie (volitelné)</Label>
            <Input
              id="send-cc"
              type="email"
              value={cc}
              onChange={(e) => setCc(e.target.value)}
              placeholder="kopie@example.com"
              disabled={sending}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="send-subject">Předmět</Label>
            <Input
              id="send-subject"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              disabled={sending}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="send-message">Zpráva</Label>
            <Textarea
              id="send-message"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              rows={8}
              disabled={sending}
              className="font-sans"
            />
          </div>

          <div className="flex items-center gap-2 rounded-md border border-border bg-muted/40 px-3 py-2 text-sm text-muted-foreground">
            <Paperclip className="h-4 w-4" />
            Příloha: <span className="font-medium text-foreground">{context.invoiceNumber}.pdf</span>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={sending}>
            Zrušit
          </Button>
          <Button variant="coral" onClick={handleSend} disabled={sending}>
            {sending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> Odesílám…
              </>
            ) : (
              <>
                <Send className="h-4 w-4" /> Odeslat
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function formatAmount(n: number, currency: string): string {
  try {
    return new Intl.NumberFormat("cs-CZ", { style: "currency", currency }).format(n);
  } catch {
    return `${n} ${currency}`;
  }
}
function formatDate(s: string): string {
  try {
    return new Date(s).toLocaleDateString("cs-CZ");
  } catch {
    return s;
  }
}

// src/components/app/SendInvoiceDialog.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Download, Loader2, Mail } from 'lucide-vue-next'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { toast } from '@/components/ui/sonner'
import { http, isApiMode, ApiError } from '@/lib/http'

// Odeslání faktury e-mailem s PDF přílohou (server, POST /invoices/{id}/send). Jen API režim —
// v náhledu zůstává poctivý fallback „stáhněte PDF". Bez SMTP na serveru přijde 503 a nic se
// nepředstírá; uživatel dostane jasnou hlášku + PDF fallback.
const props = defineProps<{
  open: boolean
  invoiceId?: string | null
  recipientEmail?: string | null
  invoiceNumber: string
  supplierName?: string | null
}>()
const emit = defineEmits<{
  'update:open': [value: boolean]
  sent: []
}>()

const apiMode = isApiMode()
const recipient = ref('')
const sending = ref(false)

watch(
  () => props.open,
  (open) => {
    if (open) recipient.value = props.recipientEmail ?? ''
  },
)

const canSend = () => apiMode && !!props.invoiceId

async function send() {
  if (!props.invoiceId) return
  if (!recipient.value.trim()) {
    toast.error('Zadejte e-mail příjemce.')
    return
  }
  sending.value = true
  try {
    await http.post(`/invoices/${props.invoiceId}/send`, { to: recipient.value.trim() })
    toast.success(`Faktura ${props.invoiceNumber} odeslána na ${recipient.value.trim()}.`)
    emit('sent')
    emit('update:open', false)
  } catch (e) {
    if (e instanceof ApiError && e.status === 503)
      toast.error(
        'Odesílání e-mailů není na serveru nastavené. Stáhněte PDF a pošlete fakturu sami.',
      )
    else if (e instanceof ApiError && e.status === 422)
      toast.error('Zkontrolujte e-mail příjemce (jedna platná adresa).')
    else if (e instanceof ApiError && e.status === 409)
      toast.error('Fakturu v tomto stavu nelze odeslat — nejdřív ji vystavte.')
    else toast.error('Fakturu se nepodařilo odeslat. Zkuste to znovu.')
    console.error(e)
  } finally {
    sending.value = false
  }
}
</script>

<template>
  <Dialog :open="open" @update:open="(o) => emit('update:open', o)">
    <DialogContent class="sm:max-w-lg">
      <template v-if="canSend()">
        <DialogHeader>
          <DialogTitle>Odeslat fakturu e-mailem</DialogTitle>
          <DialogDescription>
            Faktura {{ invoiceNumber }} se odešle s PDF přílohou
            {{ supplierName ? `jménem ${supplierName}` : '' }} a označí se jako odeslaná.
          </DialogDescription>
        </DialogHeader>

        <div class="space-y-1.5">
          <Label for="send-invoice-recipient">E-mail příjemce</Label>
          <Input
            id="send-invoice-recipient"
            v-model="recipient"
            type="email"
            placeholder="klient@firma.cz"
          />
        </div>

        <DialogFooter>
          <Button variant="outline" :disabled="sending" @click="emit('update:open', false)">
            Zrušit
          </Button>
          <Button variant="coral" :disabled="sending" @click="send">
            <Loader2 v-if="sending" class="h-4 w-4 animate-spin" />
            <Mail v-else class="h-4 w-4" />
            Odeslat
          </Button>
        </DialogFooter>
      </template>

      <template v-else>
        <DialogHeader>
          <DialogTitle>Odeslání e-mailem zatím není dostupné</DialogTitle>
          <DialogDescription>
            Fakturu {{ invoiceNumber }} stáhněte jako PDF a odešlete ji ze svého e-mailu.
          </DialogDescription>
        </DialogHeader>

        <div class="rounded-lg border border-border bg-muted/40 p-4 text-sm text-muted-foreground">
          <div class="flex items-start gap-3">
            <Download class="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <p>
              Zavřete toto okno, použijte tlačítko
              <strong class="text-foreground">Stáhnout PDF</strong> a soubor přiložte do zprávy{{
                recipientEmail ? ` pro ${recipientEmail}` : ''
              }}.
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="coral" @click="emit('update:open', false)">Rozumím</Button>
        </DialogFooter>
      </template>
    </DialogContent>
  </Dialog>
</template>
